### ISSUE TITLE
Deploy of notebook with source code fails

### ISSUE THREAD

**Issue by oli666** [rstudio/rsconnect-jupyter#154]
hi, 

I can sucessfully deploy "static" notebooks to rstudio connect using the recipe as in https://docs.rstudio.com/rsconnect-jupyter/ 

Sucessfull: 

[I 16:39:49.767 NotebookApp] Saving file at /notebook.ipynb
INFO:rsconnect_jupyter:filename = notebook.html
DEBUG:rsconnect_jupyter:added buffer: notebook.html
DEBUG:rsconnect_jupyter:manifest: {'version': 1, 'metadata': {'appmode': 'static', 'primary_html': u'notebook.html'}}
DEBUG:rsconnect_jupyter:added buffer: manifest.json
DEBUG:rsconnect_jupyter:Performing: GET /__api__/applications/12
DEBUG:rsconnect_jupyter:Performing: POST /__api__/applications/12/upload
DEBUG:rsconnect_jupyter:Performing: POST /__api__/applications/12/deploy
DEBUG:rsconnect_jupyter:Performing: GET /__api__/tasks/lI6Mu1vFYqf1xC7H
DEBUG:rsconnect_jupyter:Performing: GET /__api__/applications/12/config
[I 16:39:58.595 NotebookApp] Saving file at /notebook.ipynb
[I 16:40:38.691 NotebookApp] Saving file at /notebook.ipynb
DEBUG:rsconnect_jupyter:Performing: GET /__api__/applications?count=5&filter=min_role%3Aeditor&search=Python_Notebook1
DEBUG:rsconnect_jupyter:Performing: GET /__api__/applications/12
DEBUG:rsconnect_jupyter:Performing: GET /__api__/applications/12/config

Issues: 

[E 16:41:21.601 NotebookApp] Bundle creation failed
    Traceback (most recent call last):
      File "e:\my\path\lib\site-packages\rsconnect_jupyter\__init__.py", line 117, in post
        bundle = make_source_bundle(model, environment, ext_resources_dir, extra_files=[])
      File "e:\my\path\lib\site-packages\rsconnect_jupyter\bundle.py", line 117, in make_source_bundle
        manifest = make_source_manifest(nb_name, environment, 'jupyter-static')
      File "e:\my\path\lib\site-packages\rsconnect_jupyter\bundle.py", line 20, in make_source_manifest
        package_manager = environment['package_manager']
    KeyError: 'package_manager'
[W 16:41:21.602 NotebookApp] 500 POST /rsconnect_jupyter/deploy (::1): Bundle creation failed: 'package_manager'
[W 16:41:21.604 NotebookApp] Bundle creation failed: 'package_manager'
[E 16:41:21.605 NotebookApp] {
      "Content-Length": "387",
      "Accept-Language": "en-GB,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "X-Xsrftoken": "2|9ebcae8c|26ee3b0e8476c1e8ab15fca62d800423|1548341442",
      "X-Requested-With": "XMLHttpRequest",
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/notebooks/notebook.ipynb",

**Comment by joncfoo** [comment]
Could you try deploying this again and capture the console log and network request in the developer tools in your browser? It would be very helpful to the see both.

- press F12 to open the developer tools
- navigate to the Network tab
- attempt to deploy
- locate the network request with the 500
- click on it and find the "Form Data" or "Params" section
- take a screenshot or copy the data there

- navigate to the Console tab and copy the full output

Thanks

**Comment by oli666** [comment]
![image](https://user-images.githubusercontent.com/7488029/51692959-4158be80-1ffe-11e9-936e-d630e0535282.png)

Obviously it is an issue with pip; the pip program is, however, located in the path the message is complaing about (E:\my\path\Scripts).

**Comment by oli666** [comment]
![image](https://user-images.githubusercontent.com/7488029/51693174-bc21d980-1ffe-11e9-92dc-cfabfc2df0f1.png)

And this is the console output

**Comment by joncfoo** [comment]
Right, it doesn't look like your installation has `pip`.

Could you try using a `virtualenv` as mentioned in the docs in the Installation section and deploying again?

**Comment by joncfoo** [comment]
@oli666 are you still having this issue?

**Comment by oli666** [comment]
Unfortunately yes. Actually, the original issue occured while using a virtualenv as described in the docs. I have not had the time to give it another go, however, planning to do so the next week and provide a feedback.

**Comment by mmarchetti** [comment]
I am able to recreate this on windows 10.

**Comment by mmarchetti** [comment]
This is fixed with the changes in #156, which have been released as v1.2.1.

**Comment by sntgluca** [comment]
Dear @joncfoo , 
when trying to publish a python notebook with source code,  I get an error 500 (Unexpected response code: 500), as reported in #74 as well (which is now closed).

I am using a virtual env with rsconnect-jupyter==1.2.1.93, and as far as I can tell I am following the instructions in the documentation.

Is publishing with source code supposed to work now?
May I get some hints on how to troubleshoot?

Many thanks!

**Comment by joncfoo** [comment]
@sntgluca, could you try deploying this again and capture the console log and network request in the developer tools in your browser? It would be very helpful to the see both.

- Open the developer tools in your browser
- navigate to the Network tab
- attempt to deploy
- locate the network request with the 500
- click on it and find the "Form Data" or "Params" section
- take a screenshot or copy the data there
- navigate to the Console tab and copy the full output

**Comment by mmarchetti** [comment]
Closing this as stale. Please reopen with additional information if this is still occurring.
