### ISSUE TITLE
Cannot deploy source version to Offline rsconnect server

### ISSUE THREAD

**Issue by cotepat** [rstudio/rsconnect-jupyter#159]
I cannot publish to rsconnect server (a server that doesn't have access to internet) even though the required libraries are already installed (manually) on this server...

Here is the log :

Building Jupyter notebook...
Bundle requested Python version 3.6.8; using /usr/local/bin/python3.6 which has version 3.6.8
2019/02/06 16:41:39.906652498 Running with python "3.6.8 (default, Feb  6 2019, 13:40:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36.0.1)]" at /usr/local/bin/python3.6
2019/02/06 16:41:39.906971405 Running as user: rstudio-connect
2019/02/06 16:41:39.907482682 Creating environment: vfVXWZDC5tT75zFizmxIMQ
2019/02/06 16:41:41.187278402 Already using interpreter /usr/local/bin/python3.6
2019/02/06 16:41:41.187294137 Using base prefix '/usr/local'
2019/02/06 16:41:41.187349444 New python executable in /opt/rstudio-connect/mnt/app/python/bin/python3.6
2019/02/06 16:41:41.187383426 Also creating executable in /opt/rstudio-connect/mnt/app/python/bin/python
2019/02/06 16:41:41.187416922 Installing setuptools, pip, wheel...
2019/02/06 16:42:06.600561591 done.
2019/02/06 16:42:06.976390489 Collecting backcall==0.1.0 (from -r requirements.txt (line 1))
2019/02/06 16:42:06.981888914   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58ead00c18>: Failed to establish a new connection: [Errno 111] Connection refused',)': /simple/backcall/
2019/02/06 16:42:07.485467690   Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58ead00390>: Failed to establish a new connection: [Errno 111] Connection refused',)': /simple/backcall/
2019/02/06 16:42:08.531822437   Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58eac8ae48>: Failed to establish a new connection: [Errno 111] Connection refused',)': /simple/backcall/
2019/02/06 16:42:10.564834676   Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58eac8a240>: Failed to establish a new connection: [Errno 111] Connection refused',)': /simple/backcall/
2019/02/06 16:42:14.606884910   Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58eac8af60>: Failed to establish a new connection: [Errno 111] Connection refused',)': /simple/backcall/
2019/02/06 16:42:14.643023853   Could not find a version that satisfies the requirement backcall==0.1.0 (from -r requirements.txt (line 1)) (from versions: )
2019/02/06 16:42:14.643685237 No matching distribution found for backcall==0.1.0 (from -r requirements.txt (line 1))
2019/02/06 16:42:14.681136939 Error during installation; removing environment from cache: /opt/rstudio-connect/mnt/python-environments/pip/3.6.8/vfVXWZDC5tT75zFizmxIMQ
2019/02/06 16:42:14.729831025 pip install failed with exit code 1
Build error: exit status 1

**Comment by joncfoo** [comment]
On the Connect server you can have `pip` use an offline cache by specifying a few options in `/etc/pip.conf`:

```
[global]
no-index = true
find-links =
    file:///place/where/packages/are/available
```

You would then place the wheels or tarballs for the python packages you want in `/place/where/package/packages/are/available`

**Comment by joncfoo** [comment]
On a machine that is connected to the 'net you can grab package tarballs with: `pip install --download=/path/to/store/python/package/tarballs package1 package2 etc`

**Comment by cotepat** [comment]
It's working now. And that was easy ;-) Many thanks.
