### ISSUE TITLE
unable to build Python virtualenv

### ISSUE THREAD

**Issue by arnesond2** [rstudio/rsconnect-jupyter#174]
I have a developer trying to deploy first Jupyter Notebook to our RStudio Connect environment. He receives this error, and the deployment fails:

Building Jupyter notebook...
 Bundle requested Python version 3.6.3; using /opt/rh/rh-python36/root/usr/bin/python3.6 which has version 3.6.3
 2019/08/09 14:50:24.898609273 Running with python "3.6.3 (default, Apr 10 2019, 14:37:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]" at /opt/rh/rh-python36/root/usr/bin/python3.6
 2019/08/09 14:50:24.901802350 Running as user: rstudio-connect
 2019/08/09 14:50:24.915012802 Skipped packages: pywinpty==0.5.5,wincertstore==0.2
 2019/08/09 14:50:24.915060105 Unexpected error while building python environment: Unicode-objects must be encoded before hashing
 Build error: exit status 255

The notebook is very simple ; n=1. Tried printing 'hello world' instead and got same result.

Connect config file contains:
 [Python]
 Enabled = true
 Executable = /opt/rh/python27/root/bin/python2
 Executable = /opt/rh/rh-python36/root/bin/python3

The Python install includes:
 rh-python36-runtime-2.0-1.el7.x86_64
 rh-python36-python-virtualenv-15.1.0-2.el7.noarch
 rh-python36-python-3.6.3-7.el7.x86_64
 rh-python36-python-devel-3.6.3-7.el7.x86_64
 rh-python36-python-setuptools-36.5.0-1.el7.noarch
 rh-python36-python-libs-3.6.3-7.el7.x86_64
 rh-python36-2.0-1.el7.x86_64
 rh-python36-python-pip-9.0.1-2.el7.noarch

Is something missing?

**Comment by slopp** [comment]
@arnesond2 could you send an email to support@rstudio.com? That will ensure we have the right eyes on the problem and can you publishing quickly! Thanks

**Comment by slopp** [comment]
@koverholt  I think you suggested they open this issue - do you know what may be going on? Or should we forward and track in support?

**Comment by slopp** [comment]
@arnesond2 sorry to bounce you around a bit - ultimately we'll want to figure out the issue and fix it here, but to get the ball rolling (and make sure we don't loose track), would you mind sending an email to support@rstudio.com?

**Comment by arnesond2** [comment]
Hi Sean, I did so yesterday at your suggestion:

request (#38858<https://urldefense.proofpoint.com/v2/url?u=https-3A__support.rstudio.com_hc_requests_38858&d=DwMFaQ&c=ilBQI1lupc9Y65XwNblLtw&r=b_gNKJt89Bmguv8q8Fbr-HWUcvV7_BuMf_YIC0PsCmE&m=86lRnlA6N15WIjZleIqQV-i-SuX_y-I4QT1PRdtHVvI&s=4e8ZLCfZ5YMKfw8WSsNec52QpkhoWOqtFsFMMvRdZUY&e=>) has been received and is being reviewed by our support staff.

Our Linux server support person installed Python as follows:
Added repo rhel-server-rhscl-7-rpms
Then ran:
yum install python27
yum install rh-python36

FYI – I’ve installed on gush1aac just now and ran a couple of other yum install python commands and they loaded in some additional packages including “python-pip”

RHEL is installed with lang = en_US.UTF-8

Regards,
Dave Arneson

**Comment by arnesond2** [comment]
I am able to use Python directly on the server.
I and my Linux admin tried to find the /opt/rstudio-connect/scripts/run-diagnostics.sh script but cannot find it on the server anywhere.  

RHEL is installed with with lang = en_US.UTF-8

Added repo rhel-server-rhscl-7-rpms
Then ran:
yum install python27
yum install rh-python36

**Comment by arnesond2** [comment]
what logs are you looking for?

**Comment by arnesond2** [comment]
Rstudio version 1.1.463

**Comment by colearendt** [comment]
That looks like your RStudio version. We are looking for the RStudio Connect version, which ca often be found under the "Documentation" tab (or if you click on the "Server Documenation" link, the version number should be mentioned). It can also be determined by `/opt/rstudio-connect/bin/connect --version`

**Comment by arnesond2** [comment]
[cid:image001.png@01D55E7E.AE307840]


[cid:image002.png@01D55E7E.AE307840]

**Comment by colearendt** [comment]
The images you attached do not seem to have made it through to github, just FYI

**Comment by arnesond2** [comment]
/opt/rstudio-connect/bin/connect --version
Version: 1.6.10-3
Build: "29a6161"

**Comment by scottmmjackson** [comment]
This is being handled in RStudio Support.

To anyone with this issue, please ask your RStudio Connect Administrator to upgrade to the most recent version of RStudio Connect and see if that fixes your issue. If not, please contact RStudio Support.
