### ISSUE TITLE
Build error: Can't get matching python version because Python is disabled

### ISSUE THREAD

**Issue by sarahvch** [rstudio/rsconnect-jupyter#258]
How do I enable python?  I'm deploying to our rsconnect server using this command: 

rsconnect deploy notebook \
	--server https://my.connect.server:3939 \
	--api-key my-api-key \
	my-notebook.ipynb

checking arguments...                              [OK]
Inspecting Python environment...                 [OK]
Creating deployment bundle...                    [OK]
Uploading bundle...                              [OK]
Saving deployment data...                        [OK]

Deployment log:
Building Jupyter notebook...
Build error: Can't get matching python version because Python is disabled
Error: Task exited with status 1.

**Comment by jskress** [comment]
The administrator of your RStudio Connect instance will need to make sure Python is installed and enabled _on the machine where Connect is running_.  Enabling Python will require changes to RStudio Connect's configuration file and a restart to make those changes take effect.  [This chapter](https://docs.rstudio.com/connect/admin/python/) of the RStudio Connect Admin Guide has all the details you need to do this.

**Comment by sarahvch** [comment]
awesome thanks for your quick response! 
The admin and I have added this to the `/etc/rstudio-connect/rstudio-connect.gcfg file`

```
[Python]
Enabled = true
```
Once saved, we have been trying to restart the server and it has crashed every time. We have also tried adding: `Executable = /opt/Python/3.7.1/bin/python3.7` This doesn't seem to alter the situation in either direction. We have also built python from source as indicated in the document and this test works:  `/opt/Python/${VERSION}/bin/python${PYTHON_MAJOR} --version`

**Comment by jskress** [comment]
Your best option at this point will be to send an email to support@rstudio.com.  They will be happy to help you get things going.

**Comment by csliangy** [comment]
Exactly the same issue here.

**Comment by dareneiri** [comment]
For anyone else who stumbles here looking for a solution... 
Looking at my logs I noticed the following: 

```
2020/11/17 15:11:53 Incompatible python libraries at /opt/Python/3.7.1/bin/python3.7: Setuptools version 39.0.1 in python at /opt/Python/3.7.1/bin/python3.7 is older than the minimum required version 40.8.0.
2020/11/17 15:11:53 Error: unable to use Python on this system: Could not locate a Python installation
```
Going back to the [documentation](https://docs.rstudio.com/connect/admin/python/#python-source), I noticed I skipped a step, specifically on Setuptools. This is because the copy-paste section in the documentation does not include updating Setuptools if it's outdated

You simply need to run: 
```
sudo /opt/Python/${VERSION}/bin/pip install 'setuptools>=40.8'
```

Then restart rstudio-connect and it should not fail.

**Comment by mmarchetti** [comment]
Closing - Connect now requires python installations specified in the configuration to pass startup checks. It doesn't just omit them from the list of valid installations.
