### ISSUE TITLE
README Note

### ISSUE THREAD

**Issue by AshleyHenry15** [rstudio/rsconnect-jupyter#275]
Katie sent this information to me:

> A comment from a customer:
> Also, just FYI: in this doc/guide https://docs.rstudio.com/rsconnect-jupyter/
> The commands right after this line….
> Enable the rsconnect-jupyter extension with the following commands:
> …assume that the bin dir with jupyter and all of those commands are on the PATH or discoverable by the user.
> So, for me, that was ~/.local/bin
> I had to add that to my PATH to get those to work. That said, I used the --user flag instead of --sys-prefix because I didn’t have permissions.
> So, y’all may want to add a note in there on this; that may save some people 30 minutes or so

**Comment by annikakrilov** [comment]
@mmarchetti There was a question in #298 about this - "Should we add something to the guide to cover this issue or is this too much of an edge case?" that doesn't look like it was answered. Is this issue still worth working on, or should we close it?

**Comment by mmarchetti** [comment]
I'd prefer to stick to the currently documented path, which introduces fewer potential complications in the user setup.
