### ISSUE TITLE
404 when adding an Rstudio connect server

### ISSUE THREAD

**Issue by elimillera** [rstudio/rsconnect-jupyter#280]
I have Jupyter Notebooks running from the Rstudio Launcher and I can create and run the notebooks as expected.

When I try to add a new Connect server I have running I get the response: "An error occurred while checking the server."

Doing some digging in the inspector shows the URL "http://< RstudioServerDNSAddress >:8787/s/4566a2cb256d2f0002bc7/rsconnect_jupyter/verify_server" returning a 404. The Connect Server is running and available but the link above doesn't look to be hitting the connect server anyway.

This is running on a VM and the network ports are locked down pretty tight so I'm wondering if it could be an issue with the port its connecting too.

![image](https://user-images.githubusercontent.com/24767886/93368031-f9119400-f812-11ea-8b41-19af1310d91c.png)

**Comment by mmarchetti** [comment]
`rsconnect_juptyer` consists of 2 parts: a server extension (Python) and a notebook extension (Javascript). This sounds like the server extension isn't installed/enabled. Ensure that this command from [the docs](https://docs.rstudio.com/rsconnect-jupyter/) was run after installation: 
```
jupyter-serverextension enable --sys-prefix --py rsconnect_jupyter
```

It's also possible that this was done in a way that isn't being detected when run in the setup that you have. If that's the case, please open a ticket with RStudio Support.

**Comment by elimillera** [comment]
That you Michael. It seems there were two jupyter installations that were conflicting with each other. Removing one of them resolved the issue. Thank you!
