### ISSUE TITLE
Plugin Version Mismatch: rsconnect-jupyter has been installed incorrectly. The javascript extension version reports undefined but the server extension reports 1.4.1.

### ISSUE THREAD

**Issue by Arumugamn** [rstudio/rsconnect-jupyter#288]
Plugin Version Mismatch: rsconnect-jupyter has been installed incorrectly. The javascript extension version reports undefined but the server extension reports 1.4.1.

while Trying to publish the jupyter to Rstudio this popup error occurs. i have tried uninstall and reinstalling the rsconnect-jupyter and all its extension but no luck. please help me on this. 

![Python_Error](https://user-images.githubusercontent.com/58586307/113559343-32eb9180-95cf-11eb-9b50-b51d21765498.JPG)

**Comment by Arumugamn** [comment]
Hi, Any suggestion for the above issue ? please

**Comment by mmarchetti** [comment]
This looks like an installation problem. Since you've already tried reinstalling, I would suggest opening a ticket with RStudio support to get additional help.
