### ISSUE TITLE
publishing: make it obvious that a location needs to be selected

### ISSUE THREAD

**Issue by joncfoo** [rstudio/rsconnect-jupyter#29]
See rstudio/connect#10523

> @joncfoo as soon as I select dogfood, the Publish button becomes clickable. Note: As dogfood was already populated inPublish to field, it's wasn't obvious to me that I need to select it.

**Comment by mmarchetti** [comment]
We've made changes in this area, mainly auto-selecting the server if there is only one. Closing.
