### ISSUE TITLE
Create manifest button does not show up in the create manifest for git publishing option

### ISSUE THREAD

**Issue by vermas40** [rstudio/rsconnect-jupyter#290]
The button does not come up in the dialog box appears when you click on create manifest option.

**Comment by mmarchetti** [comment]
Are there any errors in the browser console?

**Comment by vermas40** [comment]
No there aren't

**Comment by mmarchetti** [comment]
It's probably best to open an RStudio support ticket for this.

**Comment by vermas40** [comment]
Alright, that makes sense. I will do that. 
Closing this for now. 

Thanks.
