### ISSUE TITLE
Dont see the rsconnect icon in a jupyter notebook

### ISSUE THREAD

**Issue by tauseef1234** [rstudio/rsconnect-jupyter#328]
After completing the installation steps without any errors, not able to see the rsconnect icon in jupyter notebook.

**Comment by nick-youngblut** [comment]
Same here. The docs at https://docs.posit.co/rsconnect-jupyter/usage/ don't seem to describe where the publish icon should be found, whether it differs between Jupyter Notebook and JupyterLab, and how to troubleshoot instances where the icon cannot be found.

Also, a current big limitation:

>This plugin is only for notebooks using Python kernels. Therefore, R notebooks cannot be published using this plugin.

Really, there is currently no documentation on installing R notebooks that I can find in the Posit docs.

**Comment by nick-youngblut** [comment]
At least for me, the blue publish icon is only visible for Jupyter Notebook sessions and not JupyterLab sessions. It appears that JupyterLab is not supported, although the docs are not really clear about that.

**Comment by nick-youngblut** [comment]
When I try to publish my notebook, the "publish" button is below the bottom of my screen and I cannot scroll down, so there is no way to publish! 🤣 🤣 🤣 

<img width="1089" alt="Screen Shot 2022-12-23 at 3 43 56 PM" src="https://user-images.githubusercontent.com/2468572/209413886-d637a70a-27a2-489d-be8b-544201569012.png">
