### ISSUE TITLE
Docs just describe install, but not usage

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/rsconnect-jupyter#335]
The docs at https://github.com/rstudio/rsconnect-jupyter/blob/master/docs/docs/index.md just describe the install process, but not the actually usage of rsconnect-jupyter

**Comment by mmarchetti** [comment]
Hi, the other markdown files in that directory contain the rest of the docs. A rendered version is hosted at https://docs.posit.co/rsconnect-jupyter/

**Comment by nick-youngblut** [comment]
Thank @mmarchetti !

I must have missed the link to https://docs.posit.co/rsconnect-jupyter/ from https://github.com/rstudio/rsconnect-jupyter/blob/master/docs/docs/index.md
