### ISSUE TITLE
Docs not rendered in Markdown correctly

### ISSUE THREAD

**Issue by isabelizimm** [rstudio/rsconnect-jupyter#346]
When looking at the docs, the Markdown syntax is not rendered in GitHub. Maybe it is hosted on GHPages or another location where it is rendered as expected and the README link needs to be updated? 

This is a snippet of what I am seeing when I follow the README link for docs:
⬇️ 

---

<img width="1167" alt="Screen Shot 2023-02-27 at 1 21 11 PM" src="https://user-images.githubusercontent.com/54685329/221650072-2ae66548-919b-430c-a5cd-071f17b21677.png">

**Comment by tdstein** [comment]
Hey @isabelizimm - the snippets bit is particular to mkdocs. Checkout https://github.com/rstudio/rsconnect-jupyter/blob/master/docs/README.md

**Comment by tdstein** [comment]
And the public docs are available here: https://docs.posit.co/rsconnect-jupyter/

**Comment by tdstein** [comment]
Ah, I see.

In this case, the README.md is primarily utilized by users of PyPI https://pypi.org/project/rsconnect-jupyter/

It makes sense to remove the direct link to GitHub and leave the link to the public documentation.

**Comment by annikakrilov** [comment]
Awesome, thanks! I'll grab this then :)

**Comment by annikakrilov** [comment]
Accidentally pushed to Main instead of branch - @mmarchetti reviewed/approved https://github.com/rstudio/rsconnect-jupyter/commit/5a0fcaa1c1a75bc3d3d6f3bbe766bbdb93b1a8da closing this as complete
